/* Comparing population for New Refresh */

SELECT QUARTER, COUNT(*) 
FROM [IDI_Sandpit].[DL-MAA2023-55].[master_table_202406] 
WHERE POPULATION = 1 
GROUP BY QUARTER
ORDER BY QUARTER 

SELECT QUARTER, COUNT(*) 
FROM [IDI_Sandpit].[DL-MAA2023-55].[master_table_202403] 
WHERE POPULATION = 1 
GROUP BY QUARTER
ORDER BY QUARTER

SELECT QUARTER, COUNT(*) 
FROM [IDI_Sandpit].[DL-MAA2023-55].[master_table] 
WHERE POPULATION = 1 
GROUP BY QUARTER
ORDER BY QUARTER



